### ISSUE TITLE
Properties data import into rails does not populate street_address column

### ISSUE THREAD

**Issue by LKWLaLa** [chrishenry/deltanyc-heatseek#60]
Perhaps there is a problem in the source data?

Running ``SELECT * FROM hpd_buildings LIMIT 10 \G`` returns hpd data without any `streetname` information:

```*************************** 1. row ***************************
        buildingid: 328
            boroid: 1
              boro: MN
       housenumber: 173
    lowhousenumber: 173
   highhousenumber: 173
        streetname: 
               zip: 10003
             block: 452
               lot: 32
               bin: 1006450
    communityboard: 3
       censustract: 4000
 managementprogram: PVT
dobbuildingclassid: 1
  dobbuildingclass: OLD  LAW TENEMENT
      legalstories: 5
       legalclassa: 8
       legalclassb: 0
    registrationid: 132391
         lifecycle: Building
    recordstatusid: 1
      recordstatus: Active
               bbl: 1004520032
*************************** 2. row ***************************
        buildingid: 329
            boroid: 1
              boro: MN
       housenumber: 1733
    lowhousenumber: 1733
   highhousenumber: 1735
        streetname: 
               zip: 10128
             block: 1552
               lot: 29
               bin: 1050120
    communityboard: 8
       censustract: 15400
 managementprogram: PVT
dobbuildingclassid: 1
  dobbuildingclass: OLD  LAW TENEMENT
      legalstories: 6
       legalclassa: 41
       legalclassb: 0
    registrationid: 101342
         lifecycle: Building
    recordstatusid: 1
      recordstatus: Active
               bbl: 1015520029
*************************** 3. row ***************************
        buildingid: 330
            boroid: 1
              boro: MN
       housenumber: 174
    lowhousenumber: 174
   highhousenumber: 174
        streetname: 
               zip: 10009
             block: 438
               lot: 6
               bin: 1082530
    communityboard: 3
       censustract: 3400
 managementprogram: PVT
dobbuildingclassid: 1
  dobbuildingclass: OLD  LAW TENEMENT
      legalstories: 4
       legalclassa: 5
       legalclassb: 0
    registrationid: 128480
         lifecycle: Building
    recordstatusid: 1
      recordstatus: Active
               bbl: 1004380006
*************************** 4. row ***************************
        buildingid: 331
            boroid: 1
              boro: MN
       housenumber: 1740
    lowhousenumber: 1740
   highhousenumber: 1740
        streetname: 
               zip: 10128
             block: 1570
               lot: 1
               bin: 1050720
    communityboard: 8
       censustract: 15200
 managementprogram: PVT
dobbuildingclassid: 1
  dobbuildingclass: OLD  LAW TENEMENT
      legalstories: 5
       legalclassa: 13
       legalclassb: 0
    registrationid: 111736
         lifecycle: Building
    recordstatusid: 1
      recordstatus: Active
               bbl: 1015700001
*************************** 5. row ***************************
        buildingid: 332
            boroid: 1
              boro: MN
       housenumber: 1741
    lowhousenumber: 1741
   highhousenumber: 1741
        streetname: 
               zip: 10128
             block: 1553
               lot: 23
               bin: 1050180
    communityboard: 8
       censustract: 15400
 managementprogram: PVT
dobbuildingclassid: 1
  dobbuildingclass: OLD  LAW TENEMENT
      legalstories: 5
       legalclassa: 16
       legalclassb: 0
    registrationid: 104532
         lifecycle: Building
    recordstatusid: 1
      recordstatus: Active
               bbl: 1015530023
```

Also, the pluto_nyc table seems to be lacking `address` data:

```
mysql> SELECT * FROM pluto_nyc LIMIT 10 \G
*************************** 1. row ***************************
      borough: BX
        block: 2260
          lot: 1
           cd: 201
       ct2010: 19
       cb2010: 1022
   schooldist: 7
      council: 8
      zipcode: 10454
     firecomp: L029
   policeprct: 40
   healtharea: 4700
    sanitboro: 2
sanitdistrict: 1
     sanitsub: 2A
      address: 
    zonedist1: M1-5/R8A
    zonedist2: NULL
    zonedist3: NULL
    zonedist4: NULL
     overlay1: NULL
     overlay2: NULL
      spdist1: MX-1
      spdist2: NULL
      spdist3: NULL
    ltdheight: NULL
    splitzone: N
    bldgclass: Z9
      landuse: NULL
    easements: 0
    ownertype: NULL
    ownername: 122 BRUCKNER PARTNERS
      lotarea: 15000
     bldgarea: 0
      comarea: 0
      resarea: 0
   officearea: 0
   retailarea: 0
   garagearea: 0
    strgearea: 0
   factryarea: 0
    otherarea: 0
   areasource: 7
     numbldgs: 1
    numfloors: 0
     unitsres: 0
   unitstotal: 0
     lotfront: 75
     lotdepth: 200
    bldgfront: 0
    bldgdepth: 0
          ext: NULL
     proxcode: 0
   irrlotcode: N
      lottype: 3
     bsmtcode: 5
   assessland: 130500
    assesstot: 152100
   exemptland: 0
    exempttot: 0
    yearbuilt: 0
   yearalter1: 0
   yearalter2: 0
     histdist: NULL
     landmark: NULL
     builtfar: 0
     residfar: 6.02
      commfar: 5
     facilfar: 6.5
     borocode: 2
          bbl: 2022600001
      condono: 0
    tract2010: 19
       xcoord: 1005960
       ycoord: 232162
      zonemap: 6b
       zmcode: NULL
      sanborn: 209S016
       taxmap: 20901
    edesignum: E-143
       appbbl: 0
      appdate: NULL
   plutomapid: 1
*************************** 2. row ***************************
      borough: BX
        block: 2260
          lot: 4
           cd: 201
       ct2010: 19
       cb2010: 1022
   schooldist: 7
      council: 8
      zipcode: 10454
     firecomp: L029
   policeprct: 40
   healtharea: 4700
    sanitboro: 2
sanitdistrict: 1
     sanitsub: 2A
      address: 
    zonedist1: M1-5/R8A
    zonedist2: NULL
    zonedist3: NULL
    zonedist4: NULL
     overlay1: NULL
     overlay2: NULL
      spdist1: MX-1
      spdist2: NULL
      spdist3: NULL
    ltdheight: NULL
    splitzone: N
    bldgclass: G5
      landuse: 7
    easements: 0
    ownertype: NULL
    ownername: 24 INDIAN HEAD HOLDIN
      lotarea: 13770
     bldgarea: 752
      comarea: 752
      resarea: 0
   officearea: 272
   retailarea: 0
   garagearea: 0
    strgearea: 480
   factryarea: 0
    otherarea: 0
   areasource: 2
     numbldgs: 2
    numfloors: 1
     unitsres: 0
   unitstotal: 1
     lotfront: 137.58
     lotdepth: 100
    bldgfront: 16
    bldgdepth: 16
          ext: NULL
     proxcode: 0
   irrlotcode: N
      lottype: 5
     bsmtcode: 5
   assessland: 117000
    assesstot: 293850
   exemptland: 0
    exempttot: 18225
    yearbuilt: 1931
   yearalter1: 1994
   yearalter2: 0
     histdist: NULL
     landmark: NULL
     builtfar: 0.05
     residfar: 6.02
      commfar: 5
     facilfar: 6.5
     borocode: 2
          bbl: 2022600004
      condono: 0
    tract2010: 19
       xcoord: 1006080
       ycoord: 232156
      zonemap: 6b
       zmcode: NULL
      sanborn: 209S016
       taxmap: 20901
    edesignum: E-143
       appbbl: 0
      appdate: NULL
   plutomapid: 1
*************************** 3. row ***************************
      borough: BX
        block: 2260
          lot: 10
           cd: 201
       ct2010: 19
       cb2010: 1022
   schooldist: 7
      council: 8
      zipcode: 10454
     firecomp: L029
   policeprct: 40
   healtharea: 4700
    sanitboro: 2
sanitdistrict: 1
     sanitsub: 2A
      address: 
    zonedist1: M1-5/R8A
    zonedist2: NULL
    zonedist3: NULL
    zonedist4: NULL
     overlay1: NULL
     overlay2: NULL
      spdist1: MX-1
      spdist2: NULL
      spdist3: NULL
    ltdheight: NULL
    splitzone: N
    bldgclass: F9
      landuse: 6
    easements: 0
    ownertype: P
    ownername: ANJOST CORP
      lotarea: 35000
     bldgarea: 39375
      comarea: 39375
      resarea: 0
   officearea: 0
   retailarea: 0
   garagearea: 0
    strgearea: 0
   factryarea: 39375
    otherarea: 0
   areasource: 2
     numbldgs: 1
    numfloors: 2
     unitsres: 0
   unitstotal: 1
     lotfront: 175
     lotdepth: 200
    bldgfront: 175
    bldgdepth: 200
          ext: NULL
     proxcode: 0
   irrlotcode: N
      lottype: 4
     bsmtcode: 5
   assessland: 153000
    assesstot: 822150
   exemptland: 0
    exempttot: 0
    yearbuilt: 1931
   yearalter1: 0
   yearalter2: 0
     histdist: NULL
     landmark: NULL
     builtfar: 1.13
     residfar: 6.02
      commfar: 5
     facilfar: 6.5
     borocode: 2
          bbl: 2022600010
      condono: 0
    tract2010: 19
       xcoord: 1006190
       ycoord: 232036
      zonemap: 6b
       zmcode: NULL
      sanborn: 209S016
       taxmap: 20901
    edesignum: E-143
       appbbl: 0
      appdate: NULL
   plutomapid: 1
*************************** 4. row ***************************
      borough: BX
        block: 2260
          lot: 17
           cd: 201
       ct2010: 19
       cb2010: 1022
   schooldist: 7
      council: 8
      zipcode: 10454
     firecomp: L029
   policeprct: 40
   healtharea: 4700
    sanitboro: 2
sanitdistrict: 1
     sanitsub: 2A
      address: 
    zonedist1: M1-5/R8A
    zonedist2: NULL
    zonedist3: NULL
    zonedist4: NULL
     overlay1: NULL
     overlay2: NULL
      spdist1: MX-1
      spdist2: NULL
      spdist3: NULL
    ltdheight: NULL
    splitzone: N
    bldgclass: E9
      landuse: 6
    easements: 0
    ownertype: NULL
    ownername: 144 BRUCKNER LLC
      lotarea: 2500
     bldgarea: 10625
      comarea: 10625
      resarea: 0
   officearea: 0
   retailarea: 2125
   garagearea: 0
    strgearea: 0
   factryarea: 8500
    otherarea: 0
   areasource: 2
     numbldgs: 1
    numfloors: 5
     unitsres: 0
   unitstotal: 1
     lotfront: 25
     lotdepth: 100
    bldgfront: 25
    bldgdepth: 85
          ext: NULL
     proxcode: 0
   irrlotcode: N
      lottype: 5
     bsmtcode: 5
   assessland: 33750
    assesstot: 227250
   exemptland: 0
    exempttot: 0
    yearbuilt: 1931
   yearalter1: 2001
   yearalter2: 0
     histdist: NULL
     landmark: NULL
     builtfar: 4.25
     residfar: 6.02
      commfar: 5
     facilfar: 6.5
     borocode: 2
          bbl: 2022600017
      condono: 0
    tract2010: 19
       xcoord: 1006300
       ycoord: 232033
      zonemap: 6b
       zmcode: NULL
      sanborn: 209S016
       taxmap: 20901
    edesignum: E-143
       appbbl: 0
      appdate: NULL
   plutomapid: 1
```

**Comment by LKWLaLa** [comment]
For some reason, `street_address` is still blank in my Rails Property table.  Although the hpd_buildings table does now have a street name.  👌

Also, the address column in pluto_nyc is still blank - is that something that should be fixed, or is that to be expected?

```
 borough: BX
        block: 2260
          lot: 17
           cd: 201
       ct2010: 19
       cb2010: 1022
   schooldist: 7
      council: 8
      zipcode: 10454
     firecomp: L029
   policeprct: 40
   healtharea: 4700
    sanitboro: 2
sanitdistrict: 1
     sanitsub: 2A
      address: 
    zonedist1: M1-5/R8A
    zonedist2: NULL
    zonedist3: NULL
    zonedist4: NULL
     overlay1: NULL
     overlay2: NULL
      spdist1: MX-1
      spdist2: NULL
      spdist3: NULL
    ltdheight: NULL
    splitzone: N
    bldgclass: E9
      landuse: 6
    easements: 0
    ownertype: NULL
    ownername: 144 BRUCKNER LLC
      lotarea: 2500
     bldgarea: 10625
      comarea: 10625
      resarea: 0
   officearea: 0
   retailarea: 2125
   garagearea: 0
    strgearea: 0
   factryarea: 8500
    otherarea: 0
   areasource: 2
     numbldgs: 1
    numfloors: 5
     unitsres: 0
   unitstotal: 1
     lotfront: 25
     lotdepth: 100
    bldgfront: 25
    bldgdepth: 85
          ext: NULL
     proxcode: 0
   irrlotcode: N
      lottype: 5
     bsmtcode: 5
   assessland: 33750
    assesstot: 227250
   exemptland: 0
    exempttot: 0
    yearbuilt: 1931
   yearalter1: 2001
   yearalter2: 0
     histdist: NULL
     landmark: NULL
     builtfar: 4.25
     residfar: 6.02
      commfar: 5
     facilfar: 6.5
     borocode: 2
          bbl: 2022600017
      condono: 0
    tract2010: 19
       xcoord: 1006300
       ycoord: 232033
      zonemap: 6b
       zmcode: NULL
      sanborn: 209S016
       taxmap: 20901
    edesignum: E-143
       appbbl: 0
      appdate: NULL
   plutomapid: 1
```
