### ISSUE TITLE
 hpd_registration_contacts data is in incorrect columns

### ISSUE THREAD

**Issue by LKWLaLa** [chrishenry/deltanyc-heatseek#64]
When running `SELECT * FROM hpd_registration_contacts LIMIT 10 \G`

Data is being populated into incorrect columns (generally most columns are incorrect):

- Street address is populated into `lastname`

- Zipcode is populated into `businesscity`, but `businesszip` is null

- Last name is populated into `firstname`

- First name is populated into `corporationname`

- State is in column `businessapartment`

- House number is under `middleinitial`

Etc.  (See below)

```
registrationcontactid: CorporateOwner
       registrationid: GEN.PART
                 type: 46-01-46-31 SKILLMAN REALTY LLC
   contactdescription: NULL
      corporationname: NULL
                title: NULL
            firstname: NULL
        middleinitial: 502
             lastname: EAST 79TH STREET
  businesshousenumber: BSMT.
   businessstreetname: 
    businessapartment: NY
         businesscity: 10075
        businessstate: NULL
          businesszip: NULL
*************************** 3. row ***************************
registrationcontactid: Agent
       registrationid: GEN.PART
                 type: NULL
   contactdescription: NULL
      corporationname: TOMMY
                title: NULL
            firstname: TORRES
        middleinitial: 502
             lastname: EAST 79TH STREET
  businesshousenumber: BSMT
   businessstreetname: 
    businessapartment: NY
         businesscity: 10075
        businessstate: NULL
          businesszip: NULL
*************************** 4. row ***************************
registrationcontactid: HeadOfficer
       registrationid: GEN.PART
                 type: NULL
   contactdescription: MEMBER
      corporationname: STANLEY
                title: NULL
            firstname: WASSERMAN
        middleinitial: 502
             lastname: EAST 79TH ST
  businesshousenumber: BSMT.
   businessstreetname: 
    businessapartment: NY
         businesscity: 10075
        businessstate: NULL
          businesszip: NULL
*************************** 5. row ***************************
registrationcontactid: Officer
       registrationid: GEN.PART
                 type: NULL
   contactdescription: NULL
      corporationname: ALAN
                title: NULL
            firstname: WASSERMAN
        middleinitial: 502
             lastname: EAST 79TH STREET
  businesshousenumber: BMST.
   businessstreetname: 
    businessapartment: NY
         businesscity: 10075
        businessstate: NULL
          businesszip: NULL
*************************** 6. row ***************************
registrationcontactid: SiteManager
       registrationid: GEN.PART
                 type: NULL
   contactdescription: NULL
      corporationname: ADAM
                title: NULL
            firstname: ONOPIAK
        middleinitial: NULL
             lastname: NULL
  businesshousenumber: NULL
   businessstreetname: 
    businessapartment: NULL
         businesscity: NULL
        businessstate: NULL
          businesszip: NULL
*************************** 7. row ***************************
registrationcontactid: IndividualOwner
       registrationid: INDIV
                 type: NULL
   contactdescription: NULL
      corporationname: MANUEL
                title: NULL
            firstname: BERIGUETE
        middleinitial: 1204
             lastname: OGDEN AVE
  businesshousenumber: NULL
   businessstreetname: 
    businessapartment: NY
         businesscity: 10452
        businessstate: NULL
          businesszip: NULL
```
